name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.1"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

  test:

    needs: build
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11.1
      uses: actions/setup-python@v2
      with:
        python-version: "3.11.1"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Start test
      run: xvfb-run --auto-servernum python -m unittest discover -s tests
